# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\x12\x06plugin\"\xac\x01\n\nLogRequest\x12\x1e\n\x04logs\x18\x01 \x03(\x0b\x32\x10.plugin.LogEntry\x12\x13\n\x0b\x66ilter_type\x18\x02 \x01(\t\x12\x36\n\nparameters\x18\x03 \x03(\x0b\x32\".plugin.LogRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x92\x01\n\x08LogEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08raw_json\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\x11\n\ttf_req_id\x18\x05 \x01(\t\x12\x13\n\x0btf_resource\x18\x06 \x01(\t\x12\x0f\n\x07section\x18\x07 \x01(\t\x12\x14\n\x0ctext_excerpt\x18\x08 \x01(\t\"G\n\x0bLogResponse\x12\'\n\rfiltered_logs\x18\x01 \x03(\x0b\x32\x10.plugin.LogEntry\x12\x0f\n\x07summary\x18\x02 \x01(\t2F\n\x0cLogProcessor\x12\x36\n\x0bProcessLogs\x12\x12.plugin.LogRequest\x1a\x13.plugin.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_LOGREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_LOGREQUEST']._serialized_start=25
  _globals['_LOGREQUEST']._serialized_end=197
  _globals['_LOGREQUEST_PARAMETERSENTRY']._serialized_start=148
  _globals['_LOGREQUEST_PARAMETERSENTRY']._serialized_end=197
  _globals['_LOGENTRY']._serialized_start=200
  _globals['_LOGENTRY']._serialized_end=346
  _globals['_LOGRESPONSE']._serialized_start=348
  _globals['_LOGRESPONSE']._serialized_end=419
  _globals['_LOGPROCESSOR']._serialized_start=421
  _globals['_LOGPROCESSOR']._serialized_end=491
# @@protoc_insertion_point(module_scope)
